# Generated by Django 3.2.6 on 2021-08-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('if_id', models.AutoField(primary_key=True, serialize=False)),
                ('if_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('request_body_param', models.TextField()),
                ('response_body_param', models.TextField()),
            ],
        ),
    ]
